@startuml
'title INCOSE Handbook Ontology

'scale 1000 width
'skinparam packageStyle frame
'skinparam linetype polyline
'top to bottom direction
hide empty members
'hide circle
'hide stereotype 

' spare colours from the palette... #9EB9F3,#F6CF71,#66C5CC,#B497E7,#D3B484,#B3B3B3

class enabler as "Enabler" << (E,#8BE0A4) >> 
class control as "Control"<< (C,#C9DB74) >>
class io as "Input/Output" << (I,#DCB0F2) >>
class activity as "Activity" << (A,#87C55F) >>
class process as "Process" << (P,#FE88B1) >>

io - process : inputs into >
process -- io : outputs >
process - activity : has part >
control -- process : governs >
process -- enabler : enables <
@enduml
